unique_ids:
  assets:
    standard-page.html: FZBU2SMDGJOVJSTT2PB6YAFN4CNXYVFU
    theme.css: 7T2S2UZ4JA7VB3OCMCK7WHUFTF2ATA2U
  forms:
    Form1: SCANZAA6LZLV3SGZIU7H2Q34QMLXAA5O
  modules: {}
  scripts: {}
  server_modules: {}
